version: 1.0.{build}

image:
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Release

before_build:
  - ps: nuget restore

artifacts:
  - path: x64\Release\mpv-launcher.exe
    name: mpv-launcher.exe

deploy:
  release: mpv-launcher-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: X4NgNZcn4mzGoEKUZLK6VJxcn3m+A9SKOpVa2opdLRfwKzXx6AfKTWMr2ocsMXuF
